type ActionType = string;

export const ASYNC_GET_ARRIVALS_LIST: ActionType = 'ASYNC_GET_ARRIVALS_LIST';
export const ASYNC_GET_ARRIVALS_LIST_SUCCESS: ActionType = 'ASYNC_GET_ARRIVALS_LIST_SUCCESS';
export const ASYNC_GET_ARRIVALS_LIST_ERROR: ActionType = 'ASYNC_GET_ARRIVALS_LIST_ERROR';
