type ActionType = string;

export const ASYNC_GET_DEPARTURES_LIST: ActionType = 'ASYNC_GET_DEPARTURES_LIST';
export const TOGGLE_DEPARTURES_LOADING: ActionType = 'TOGGLE_DEPARTURES_LOADING';
export const ASYNC_GET_DEPARTURES_LIST_SUCCESS: ActionType = 'ASYNC_GET_DEPARTURES_LIST_SUCCESS';
export const ASYNC_GET_DEPARTURES_LIST_ERROR: ActionType = 'ASYNC_GET_DEPARTURES_LIST_ERROR';
